import cv2
o = cv2.imread("lena.jpg",cv2.IMREAD_GRAYSCALE)
r1 = cv2.pyrUp(o)
r2 = cv2.pyrUp(r1)
r3 = cv2.pyrUp(r2)
print("o's shape",o.shape)
print("r1's shape",r1.shape)
print("r2's shape",r2.shape)
print("r3's shape",r3.shape)
cv2.imshow("original",o)
cv2.imshow("r1",r1)
cv2.imshow("r2",r2)
cv2.imshow("r3",r3)
cv2.waitKey()
cv2.destroyAllWindows()

